[build]
  publish = "src"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
    frame-ancestors 'none';
    base-uri 'none';
    default-src 'self';
    connect-src https://plausible.io;
    img-src 'self';
    object-src 'none';
    script-src https://plausible.io/js/plausible.js;
    style-src 'self' 'unsafe-inline';
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/Inter.var.woff2*"
  [headers.values]
    cache-control = '''
    public,
    no-transform,
    immutable,
    max-age=31536000'''

[[plugins]]
  package = "netlify-plugin-no-more-404"

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
    entryPoints = [
    "*.html",
  ]

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.0 # We could bump this up if we support PWA in future
  [plugins.inputs.audits]
    output_path = "lighthouse/index.html"
