# Explicitly sets publish directory
# Right now we have no build, so we can just push `src` out
[build]
  command = "yarn build"
  publish = "dist"

# Adds Content Security Policy and other security features
# If your scripts won't run and your images won't load,
# it's probably because this is locked down pretty tight.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
    frame-ancestors 'none';
    base-uri 'none';
    default-src 'self';
    connect-src https://plausible.io;
    img-src 'self' https://res.cloudinary.com;
    object-src 'none';
    script-src https://plausible.io/js/plausible.js 'unsafe-inline';
    style-src 'self' 'unsafe-inline';
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

# A special Content Security Policy for Lighthouse
[[headers]]
  for = "/lighthouse/*"
  [headers.values]
    Content-Security-Policy = """
    frame-ancestors 'none';
    base-uri 'none';
    default-src 'self';
    img-src data:;
    object-src 'none';
    script-src 'unsafe-inline';
    style-src 'self' 'unsafe-inline';
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

# Helps prevent some very noticeable FOUT on repeat visits
[[headers]]
  for = "/Inter.var.woff2*"
  [headers.values]
    cache-control = '''
    public,
    no-transform,
    immutable,
    max-age=31536000'''

# Builds `/sitemap.xml`
# https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Runs Lighthouse on PRs, shouts if we fall under any thresholds
# https://github.com/netlify/netlify-plugin-lighthouse
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [[plugins.inputs.audits]]
    output_path = "lighthouse/index.html"

    [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9
      pwa = 0.0 # We could bump this up if we support PWA in future

# Warns if we remove a file, breaking an internal link
# https://github.com/sw-yx/netlify-plugin-no-more-404
[[plugins]]
  package = "netlify-plugin-no-more-404"

# Reports on broken links, fragments, redirect chains etc
# https://github.com/munter/netlify-plugin-checklinks
[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
    entryPoints = [
    "sitemap.xml",
    ]

    todoPatterns = [
      "lighthouse/"
    ]
